spring.application.name=dr_appl

spring.datasource.url=jdbc:mysql://localhost:3306/dr_appl?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


spring.security.user.name=joe@gm.com
spring.security.user.password=12345
spring.security.user.roles=USER   